### ISSUE TITLE
[PE-D] Out of range uncatch exception

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-F10-2/tp#143]
Program exits abruptly when I try to delete an item out of range
e.g. delete 5 when there is only 4 items

![image.png](https://raw.githubusercontent.com/kktai1512/ped/main/files/d7407eed-55db-4d52-b001-b6d1ef6a8a0e.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: kktai1512/ped#5

**Comment by IncompetentDev** [comment]
Wrong exception caught :X

Should have caught IndexOutOfBounds, not ArrayIndexOutOfBounds.
