### ISSUE TITLE
[PE-D] Allow conflicts of bookings

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-F10-2/tp#147]
![image.png](https://raw.githubusercontent.com/kktai1512/ped/main/files/3706d1ed-e5be-48ad-bcae-b18862e0afb4.png)

I borrowed the same item multiple times and the program allows me to do so 

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: kktai1512/ped#8

**Comment by lestersimjj** [comment]
Fix by #163 

An exception is thrown if the user enters a borrowing that conflicts with existing borrowings.
