### ISSUE TITLE
[PE-D] Index out of range for borrow 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-F10-2/tp#149]
![image.png](https://raw.githubusercontent.com/kktai1512/ped/main/files/ef57b44f-d605-41bc-ae00-0d8ad9086f99.png)

Again, program exits abruptly if index entered is out of range

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: kktai1512/ped#9

**Comment by lestersimjj** [comment]
Fix by #163
