### ISSUE TITLE
[PE-D] Start date earlier than end date

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-F10-2/tp#150]
![image.png](https://raw.githubusercontent.com/kktai1512/ped/main/files/be4568c0-976f-4aff-b647-983d5c4a00df.png)

There are no errors if i make the start date earlier than end date

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: kktai1512/ped#10

**Comment by lestersimjj** [comment]
Fix by #163
