### ISSUE TITLE
[PE-D] Wrong format not detected

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-F10-2/tp#156]
![image.png](https://raw.githubusercontent.com/Demonshaha/ped/main/files/fe52157d-9b1b-489e-b195-fc9310eddd1b.png)
when I input the wrong format, the program's exception cannot catch succesfully

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Demonshaha/ped#6

**Comment by IncompetentDev** [comment]
Resolution:
1. Check `arguments` in `InputParser` before creating `ListCommand`. This issue extends to `ExitCommand` and `HelpCommand` as well, since they are created without checking `arguments`.
2. OR inform user through user guide that these commands will disregard additional arguments?
