### ISSUE TITLE
[PE-D] User able to borrow duplicates of the same index item within the same duration

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-F10-2/tp#159]
![duplicates.png](https://raw.githubusercontent.com/HansHengGit/ped/main/files/bc889653-9ccd-4253-9932-fa6e5768106e.png)

As seen in the screen shot, the user is able to borrow duplicated items by typing the same borrow command over and over again.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: HansHengGit/ped#10

**Comment by lestersimjj** [comment]
Fix by #163 

An exception is thrown if the user enters a borrowing that conflicts with existing borrowings.
