### ISSUE TITLE
Code Review for Jasper

### ISSUE THREAD

**Issue by nishanthelango** [AY2122S2-CS2113-F10-2/tp#160]
@quitejasper

![image](https://user-images.githubusercontent.com/37863640/161382381-3e17eb7e-8591-4d17-8439-703941bba614.png)
Try to avoid arrowhead code. Consider extracting some of the logic into methods for better readbility.

![image](https://user-images.githubusercontent.com/37863640/161382562-49c3b93a-a996-4900-b90f-baeafd47b8f3.png)
There should be an empty line between the description and parameters section for method header comments.

**Comment by lestersimjj** [comment]
Wrote methods to abstract the arrowhead codes for a similar issue in `ListCurrentBorrowingsCommand`. Might be able to reference to/improve on #179?
