### ISSUE TITLE
Code Review for Hwee Thern

### ISSUE THREAD

**Issue by nishanthelango** [AY2122S2-CS2113-F10-2/tp#161]
@IncompetentDev 

![image](https://user-images.githubusercontent.com/37863640/161382813-6c1280f6-ff56-4e52-ae3f-b7e5c5042356.png)
There should be punctuation behind each parameter description to comply with the coding standard.

![image](https://user-images.githubusercontent.com/37863640/161383061-5974ae4c-ce81-4591-a21e-2c7de230a80f.png)
There should be an empty line between the description and parameters section in method header comments.

**Comment by IncompetentDev** [comment]
First screenshot is from ArgumentTokenizer.

Second screenshot is from SearchCommand.
