### ISSUE TITLE
Code Review for Lester

### ISSUE THREAD

**Issue by nishanthelango** [AY2122S2-CS2113-F10-2/tp#162]
@lestersimjj 

![image](https://user-images.githubusercontent.com/37863640/161383889-6c6b8f9a-4f32-4411-9372-9533e467181d.png)
Try to avoid arrowhead code. Consider extracting some of the logic into methods for better readability.

![image](https://user-images.githubusercontent.com/37863640/161383912-8601beec-2978-4292-b0a6-fd26a01cb761.png)
The first sentence should start in the form "Adds ...". There should be an empty line between the description and parameter section.

![image](https://user-images.githubusercontent.com/37863640/161384046-910d5394-4157-42ee-97ee-936659457752.png)
There should be punctuation behind each of the parameters, to comply with the coding standard.

**Comment by lestersimjj** [comment]
Fix by #179
