### ISSUE TITLE
Update listcb, listob, listfb to not show lost items

### ISSUE THREAD

**Issue by lestersimjj** [AY2122S2-CS2113-F10-2/tp#182]
With reference to #120, `listcb`, `listob`, `listfb` commands should not show borrow records of items that are marked as lost.

**Comment by lestersimjj** [comment]
#189

**Comment by quitejasper** [comment]
Do we need to show lost items if they are deleted through the lost command?

We can add in the UG that we assume lost items are only lost when not borrowed.

**Comment by lestersimjj** [comment]
Nope, we don't have to show borrow records of lost items.

When items are lost, they are deleted from the internal itemList. If we run `listcb`/ `listfb`/`listob` commands, it iterates through the itemList which now do not consist of lost items.
