### ISSUE TITLE
[BUG] Possible bug when changing days

### ISSUE THREAD

**Issue by IncompetentDev** [AY2122S2-CS2113-F10-2/tp#183]
**Describe the bug**
When creating a BorrowRecord, the status of the borrowrecord is determined at the time the code is run. EditCommand creates a new instance as a placeholder, which may result in differing borrowrecord statuses.

**To Reproduce**
1. Set time to the next day.
2. Try to edit a command
3. The resulting borrowrecord status may change (only for that record!)

**Expected behavior**
Either no change to the borrowrecord, or an entire-program update at 12am.
This is easily fixable if the user stops the program before 12am and relaunches it after 12pm.

**Comment by IncompetentDev** [comment]
This may have unintended consequences, but I cant think of any right now.

**Comment by IncompetentDev** [comment]
Let's just fix this through a note in the user guide.

**Comment by lestersimjj** [comment]
Fix by #190
