### ISSUE TITLE
AddCommandParserTest Input Format Differs from UserGuide

### ISSUE THREAD

**Issue by lestersimjj** [AY2122S2-CS2113-F10-2/tp#87]
In the UserGuide, the AddCommand takes in the user input `add n/Paper Cup q/25 d/100ml paper cups`. However, the current test takes in the user input `add /n Paper Cup /d 25ml cups /q 25`.

Should the testInputFormat be in the following string format with no spaces between the prefix and argument?

```
String testInputFormat = " %s%s %s%s %s%s";
```

https://github.com/AY2122S2-CS2113-F10-2/tp/blob/71a5f8527679487460115a19a5bd10d6cb2ac311/src/test/java/seedu/duke/parser/AddCommandParserTest.java#L24-L31

This issue repeats in other test methods defined.

**Comment by IncompetentDev** [comment]
Wrongly closed.
